/*
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.segment.publicapi.models;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.segment.publicapi.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Returns a subscription for a given subscription id. */
public class GetSubscriptionFromDestinationAlphaOutput {
    public static final String SERIALIZED_NAME_SUBSCRIPTION = "subscription";

    @SerializedName(SERIALIZED_NAME_SUBSCRIPTION)
    private DestinationSubscription subscription;

    public GetSubscriptionFromDestinationAlphaOutput() {}

    public GetSubscriptionFromDestinationAlphaOutput subscription(
            DestinationSubscription subscription) {

        this.subscription = subscription;
        return this;
    }

    /**
     * Get subscription
     *
     * @return subscription
     */
    @javax.annotation.Nonnull
    public DestinationSubscription getSubscription() {
        return subscription;
    }

    public void setSubscription(DestinationSubscription subscription) {
        this.subscription = subscription;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSubscriptionFromDestinationAlphaOutput getSubscriptionFromDestinationAlphaOutput =
                (GetSubscriptionFromDestinationAlphaOutput) o;
        return Objects.equals(
                this.subscription, getSubscriptionFromDestinationAlphaOutput.subscription);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscription);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetSubscriptionFromDestinationAlphaOutput {\n");
        sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("subscription");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("subscription");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     GetSubscriptionFromDestinationAlphaOutput
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!GetSubscriptionFromDestinationAlphaOutput.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " GetSubscriptionFromDestinationAlphaOutput is not found in"
                                    + " the empty JSON string",
                                GetSubscriptionFromDestinationAlphaOutput.openapiRequiredFields
                                        .toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!GetSubscriptionFromDestinationAlphaOutput.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `GetSubscriptionFromDestinationAlphaOutput` properties."
                                        + " JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField :
                GetSubscriptionFromDestinationAlphaOutput.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // validate the required field `subscription`
        DestinationSubscription.validateJsonElement(jsonObj.get("subscription"));
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!GetSubscriptionFromDestinationAlphaOutput.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes
                // 'GetSubscriptionFromDestinationAlphaOutput' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<GetSubscriptionFromDestinationAlphaOutput> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(GetSubscriptionFromDestinationAlphaOutput.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<GetSubscriptionFromDestinationAlphaOutput>() {
                        @Override
                        public void write(
                                JsonWriter out, GetSubscriptionFromDestinationAlphaOutput value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public GetSubscriptionFromDestinationAlphaOutput read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of GetSubscriptionFromDestinationAlphaOutput given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of GetSubscriptionFromDestinationAlphaOutput
     * @throws IOException if the JSON string is invalid with respect to
     *     GetSubscriptionFromDestinationAlphaOutput
     */
    public static GetSubscriptionFromDestinationAlphaOutput fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, GetSubscriptionFromDestinationAlphaOutput.class);
    }

    /**
     * Convert an instance of GetSubscriptionFromDestinationAlphaOutput to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
