/*
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.segment.publicapi.models;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.segment.publicapi.JSON;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Function webhook input. */
public class HandleWebhookInput {
    public static final String SERIALIZED_NAME_W = "w";

    @SerializedName(SERIALIZED_NAME_W)
    private String w;

    public static final String SERIALIZED_NAME_N = "n";

    @SerializedName(SERIALIZED_NAME_N)
    private String n;

    public static final String SERIALIZED_NAME_T = "t";

    @SerializedName(SERIALIZED_NAME_T)
    private String t;

    public static final String SERIALIZED_NAME_S = "s";

    @SerializedName(SERIALIZED_NAME_S)
    private String s;

    public HandleWebhookInput() {}

    public HandleWebhookInput w(String w) {

        this.w = w;
        return this;
    }

    /**
     * The Workspace id.
     *
     * @return w
     */
    @javax.annotation.Nonnull
    public String getW() {
        return w;
    }

    public void setW(String w) {
        this.w = w;
    }

    public HandleWebhookInput n(String n) {

        this.n = n;
        return this;
    }

    /**
     * The webhook nonce.
     *
     * @return n
     */
    @javax.annotation.Nonnull
    public String getN() {
        return n;
    }

    public void setN(String n) {
        this.n = n;
    }

    public HandleWebhookInput t(String t) {

        this.t = t;
        return this;
    }

    /**
     * The webhook timestamp.
     *
     * @return t
     */
    @javax.annotation.Nonnull
    public String getT() {
        return t;
    }

    public void setT(String t) {
        this.t = t;
    }

    public HandleWebhookInput s(String s) {

        this.s = s;
        return this;
    }

    /**
     * The webhook signature.
     *
     * @return s
     */
    @javax.annotation.Nonnull
    public String getS() {
        return s;
    }

    public void setS(String s) {
        this.s = s;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HandleWebhookInput handleWebhookInput = (HandleWebhookInput) o;
        return Objects.equals(this.w, handleWebhookInput.w)
                && Objects.equals(this.n, handleWebhookInput.n)
                && Objects.equals(this.t, handleWebhookInput.t)
                && Objects.equals(this.s, handleWebhookInput.s);
    }

    @Override
    public int hashCode() {
        return Objects.hash(w, n, t, s);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class HandleWebhookInput {\n");
        sb.append("    w: ").append(toIndentedString(w)).append("\n");
        sb.append("    n: ").append(toIndentedString(n)).append("\n");
        sb.append("    t: ").append(toIndentedString(t)).append("\n");
        sb.append("    s: ").append(toIndentedString(s)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("w");
        openapiFields.add("n");
        openapiFields.add("t");
        openapiFields.add("s");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("w");
        openapiRequiredFields.add("n");
        openapiRequiredFields.add("t");
        openapiRequiredFields.add("s");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to HandleWebhookInput
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!HandleWebhookInput.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in HandleWebhookInput is not found in the"
                                        + " empty JSON string",
                                HandleWebhookInput.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!HandleWebhookInput.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                        + " `HandleWebhookInput` properties. JSON: %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : HandleWebhookInput.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("w").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `w` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("w").toString()));
        }
        if (!jsonObj.get("n").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `n` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("n").toString()));
        }
        if (!jsonObj.get("t").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `t` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("t").toString()));
        }
        if (!jsonObj.get("s").isJsonPrimitive()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `s` to be a primitive type in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("s").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!HandleWebhookInput.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'HandleWebhookInput' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<HandleWebhookInput> thisAdapter =
                    gson.getDelegateAdapter(this, TypeToken.get(HandleWebhookInput.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<HandleWebhookInput>() {
                        @Override
                        public void write(JsonWriter out, HandleWebhookInput value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public HandleWebhookInput read(JsonReader in) throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of HandleWebhookInput given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of HandleWebhookInput
     * @throws IOException if the JSON string is invalid with respect to HandleWebhookInput
     */
    public static HandleWebhookInput fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, HandleWebhookInput.class);
    }

    /**
     * Convert an instance of HandleWebhookInput to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
