/*
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.segment.publicapi.models;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.segment.publicapi.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Output to List all Destinations from an Audience. */
public class ListDestinationsFromAudienceAlphaOutput {
    public static final String SERIALIZED_NAME_CONNECTIONS = "connections";

    @SerializedName(SERIALIZED_NAME_CONNECTIONS)
    private List<SimpleDestination> connections = new ArrayList<>();

    public static final String SERIALIZED_NAME_PAGINATION = "pagination";

    @SerializedName(SERIALIZED_NAME_PAGINATION)
    private PaginationOutput pagination;

    public ListDestinationsFromAudienceAlphaOutput() {}

    public ListDestinationsFromAudienceAlphaOutput connections(
            List<SimpleDestination> connections) {

        this.connections = connections;
        return this;
    }

    public ListDestinationsFromAudienceAlphaOutput addConnectionsItem(
            SimpleDestination connectionsItem) {
        if (this.connections == null) {
            this.connections = new ArrayList<>();
        }
        this.connections.add(connectionsItem);
        return this;
    }

    /**
     * A list of connection results.
     *
     * @return connections
     */
    @javax.annotation.Nonnull
    public List<SimpleDestination> getConnections() {
        return connections;
    }

    public void setConnections(List<SimpleDestination> connections) {
        this.connections = connections;
    }

    public ListDestinationsFromAudienceAlphaOutput pagination(PaginationOutput pagination) {

        this.pagination = pagination;
        return this;
    }

    /**
     * Get pagination
     *
     * @return pagination
     */
    @javax.annotation.Nullable
    public PaginationOutput getPagination() {
        return pagination;
    }

    public void setPagination(PaginationOutput pagination) {
        this.pagination = pagination;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListDestinationsFromAudienceAlphaOutput listDestinationsFromAudienceAlphaOutput =
                (ListDestinationsFromAudienceAlphaOutput) o;
        return Objects.equals(this.connections, listDestinationsFromAudienceAlphaOutput.connections)
                && Objects.equals(
                        this.pagination, listDestinationsFromAudienceAlphaOutput.pagination);
    }

    @Override
    public int hashCode() {
        return Objects.hash(connections, pagination);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ListDestinationsFromAudienceAlphaOutput {\n");
        sb.append("    connections: ").append(toIndentedString(connections)).append("\n");
        sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("connections");
        openapiFields.add("pagination");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("connections");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     ListDestinationsFromAudienceAlphaOutput
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!ListDestinationsFromAudienceAlphaOutput.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in"
                                    + " ListDestinationsFromAudienceAlphaOutput is not found in the"
                                    + " empty JSON string",
                                ListDestinationsFromAudienceAlphaOutput.openapiRequiredFields
                                        .toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!ListDestinationsFromAudienceAlphaOutput.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                    + " `ListDestinationsFromAudienceAlphaOutput` properties. JSON:"
                                    + " %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : ListDestinationsFromAudienceAlphaOutput.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the json data is an array
        if (!jsonObj.get("connections").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `connections` to be an array in the JSON string but"
                                    + " got `%s`",
                            jsonObj.get("connections").toString()));
        }

        JsonArray jsonArrayconnections = jsonObj.getAsJsonArray("connections");
        // validate the required field `connections` (array)
        for (int i = 0; i < jsonArrayconnections.size(); i++) {
            SimpleDestination.validateJsonElement(jsonArrayconnections.get(i));
        }
        ;
        // validate the optional field `pagination`
        if (jsonObj.get("pagination") != null && !jsonObj.get("pagination").isJsonNull()) {
            PaginationOutput.validateJsonElement(jsonObj.get("pagination"));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!ListDestinationsFromAudienceAlphaOutput.class.isAssignableFrom(
                    type.getRawType())) {
                return null; // this class only serializes 'ListDestinationsFromAudienceAlphaOutput'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ListDestinationsFromAudienceAlphaOutput> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(ListDestinationsFromAudienceAlphaOutput.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<ListDestinationsFromAudienceAlphaOutput>() {
                        @Override
                        public void write(
                                JsonWriter out, ListDestinationsFromAudienceAlphaOutput value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public ListDestinationsFromAudienceAlphaOutput read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of ListDestinationsFromAudienceAlphaOutput given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of ListDestinationsFromAudienceAlphaOutput
     * @throws IOException if the JSON string is invalid with respect to
     *     ListDestinationsFromAudienceAlphaOutput
     */
    public static ListDestinationsFromAudienceAlphaOutput fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, ListDestinationsFromAudienceAlphaOutput.class);
    }

    /**
     * Convert an instance of ListDestinationsFromAudienceAlphaOutput to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
