/*
 * Segment Public API
 * The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.  All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.  See the next sections for more information on how to use the Segment Public API.
 *
 * Contact: friends@segment.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.segment.publicapi.models;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.segment.publicapi.JSON;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Updates the schema for a Warehouse/sources pair. */
public class UpdateSelectiveSyncForWarehouseV1Input {
    public static final String SERIALIZED_NAME_SYNC_OVERRIDES = "syncOverrides";

    @SerializedName(SERIALIZED_NAME_SYNC_OVERRIDES)
    private List<WarehouseSyncOverrideV1> syncOverrides = new ArrayList<>();

    public UpdateSelectiveSyncForWarehouseV1Input() {}

    public UpdateSelectiveSyncForWarehouseV1Input syncOverrides(
            List<WarehouseSyncOverrideV1> syncOverrides) {

        this.syncOverrides = syncOverrides;
        return this;
    }

    public UpdateSelectiveSyncForWarehouseV1Input addSyncOverridesItem(
            WarehouseSyncOverrideV1 syncOverridesItem) {
        if (this.syncOverrides == null) {
            this.syncOverrides = new ArrayList<>();
        }
        this.syncOverrides.add(syncOverridesItem);
        return this;
    }

    /**
     * A list of sync schema overrides to apply to this Warehouse.
     *
     * @return syncOverrides
     */
    @javax.annotation.Nonnull
    public List<WarehouseSyncOverrideV1> getSyncOverrides() {
        return syncOverrides;
    }

    public void setSyncOverrides(List<WarehouseSyncOverrideV1> syncOverrides) {
        this.syncOverrides = syncOverrides;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateSelectiveSyncForWarehouseV1Input updateSelectiveSyncForWarehouseV1Input =
                (UpdateSelectiveSyncForWarehouseV1Input) o;
        return Objects.equals(
                this.syncOverrides, updateSelectiveSyncForWarehouseV1Input.syncOverrides);
    }

    @Override
    public int hashCode() {
        return Objects.hash(syncOverrides);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateSelectiveSyncForWarehouseV1Input {\n");
        sb.append("    syncOverrides: ").append(toIndentedString(syncOverrides)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("syncOverrides");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("syncOverrides");
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to
     *     UpdateSelectiveSyncForWarehouseV1Input
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!UpdateSelectiveSyncForWarehouseV1Input.openapiRequiredFields
                    .isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(
                        String.format(
                                "The required field(s) %s in UpdateSelectiveSyncForWarehouseV1Input"
                                        + " is not found in the empty JSON string",
                                UpdateSelectiveSyncForWarehouseV1Input.openapiRequiredFields
                                        .toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!UpdateSelectiveSyncForWarehouseV1Input.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(
                        String.format(
                                "The field `%s` in the JSON string is not defined in the"
                                    + " `UpdateSelectiveSyncForWarehouseV1Input` properties. JSON:"
                                    + " %s",
                                entry.getKey(), jsonElement.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : UpdateSelectiveSyncForWarehouseV1Input.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(
                        String.format(
                                "The required field `%s` is not found in the JSON string: %s",
                                requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        // ensure the json data is an array
        if (!jsonObj.get("syncOverrides").isJsonArray()) {
            throw new IllegalArgumentException(
                    String.format(
                            "Expected the field `syncOverrides` to be an array in the JSON string"
                                    + " but got `%s`",
                            jsonObj.get("syncOverrides").toString()));
        }

        JsonArray jsonArraysyncOverrides = jsonObj.getAsJsonArray("syncOverrides");
        // validate the required field `syncOverrides` (array)
        for (int i = 0; i < jsonArraysyncOverrides.size(); i++) {
            WarehouseSyncOverrideV1.validateJsonElement(jsonArraysyncOverrides.get(i));
        }
        ;
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!UpdateSelectiveSyncForWarehouseV1Input.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'UpdateSelectiveSyncForWarehouseV1Input'
                // and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<UpdateSelectiveSyncForWarehouseV1Input> thisAdapter =
                    gson.getDelegateAdapter(
                            this, TypeToken.get(UpdateSelectiveSyncForWarehouseV1Input.class));

            return (TypeAdapter<T>)
                    new TypeAdapter<UpdateSelectiveSyncForWarehouseV1Input>() {
                        @Override
                        public void write(
                                JsonWriter out, UpdateSelectiveSyncForWarehouseV1Input value)
                                throws IOException {
                            JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                            elementAdapter.write(out, obj);
                        }

                        @Override
                        public UpdateSelectiveSyncForWarehouseV1Input read(JsonReader in)
                                throws IOException {
                            JsonElement jsonElement = elementAdapter.read(in);
                            validateJsonElement(jsonElement);
                            return thisAdapter.fromJsonTree(jsonElement);
                        }
                    }.nullSafe();
        }
    }

    /**
     * Create an instance of UpdateSelectiveSyncForWarehouseV1Input given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of UpdateSelectiveSyncForWarehouseV1Input
     * @throws IOException if the JSON string is invalid with respect to
     *     UpdateSelectiveSyncForWarehouseV1Input
     */
    public static UpdateSelectiveSyncForWarehouseV1Input fromJson(String jsonString)
            throws IOException {
        return JSON.getGson().fromJson(jsonString, UpdateSelectiveSyncForWarehouseV1Input.class);
    }

    /**
     * Convert an instance of UpdateSelectiveSyncForWarehouseV1Input to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
