name: Publish to Maven Central on VERSION change

on:
  push:
    branches:
      - master
    paths:
      - 'VERSION'

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest-large
    permissions:
      contents: read

    env:
      MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5

      - name: Set up Java & Maven for Central
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9  # v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven

          # for central-publishing-maven-plugin
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

          # import the private key only
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: mvn -B clean deploy --no-transfer-progress
